defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 30
  timeout: 5000
  min_messages: warning

development:
  <<: *defaults
  database: nebel_development

test:
  <<: *defaults
  database: nebel_test
